  # basic configs
basic_config:
  project_path: "/home/hont/Engagement_Detection"
  time_process: 0.2 # Every time_process seconds, pickup 1 frame to process
  #source_video: "https://www.youtube.com/watch?v=gunaWMrfOoc"
  source_video: "/home/hont/input_video/input1.mp4"
  #source_video: 0

  # kind of algorithms configs
type_config:
  type_faceDetection: "mtcnn" # haarcascade_faceDetection|mtcnn
  type_emotionDetection: "haarcascade_emotionDetection" # haarcascade_emotionDetection|mini_xception_emotionDetection
  type_landMaskDetection: "68_landmarks" # haarcascade
  type_eyeGazeEstimation: "pnp_algorithm" # pnp_algorithm

  # three kinds of our methods: concentration_index, traditional_mapping, math_method
method_mapping_config: 
  method_mapping: "traditional_mapping"
  
  # algorithm settings configs
algorthms_settings_config:
  turnOn_face_identification: True
  turnOn_emotion_detection: True
  turnOn_eyeGaze_estimation: True

  # database configs
database_config:
  turnOn_storageDB: False
  turnOn_resetDB: False

  # processing settings
processing_settings:
  # -------

  outputFile_path: "/home/hont/input_video/output.mp4"
  # -------
  showFrame: False
  # -------
  drawOnFrame: True
  drawRunningTime: False